Refactor Dockerfile and inference server for improved GPU load reporting and SSL setup; update Jetson tutorial with new inference command

diff --git a/ai_inference/jetson-inference/Dockerfile b/ai_inference/jetson-inference/Dockerfile
--- a/ai_inference/jetson-inference/Dockerfile
+++ b/ai_inference/jetson-inference/Dockerfile
@@ -1,135 +1,38 @@
-# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
-#
-# Permission is hereby granted, free of charge, to any person obtaining a
-# copy of this software and associated documentation files (the "Software"),
-# to deal in the Software without restriction, including without limitation
-# the rights to use, copy, modify, merge, publish, distribute, sublicense,
-# and/or sell copies of the Software, and to permit persons to whom the
-# Software is furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
-# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
-# DEALINGS IN THE SOFTWARE.
-#
-# Build this Dockerfile by running the following commands:
-#
-#     $ cd /path/to/your/jetson-inference
-#     $ docker/build.sh
-#
-# Also you should set your docker default-runtime to nvidia:
-#     https://github.com/dusty-nv/jetson-containers#docker-default-runtime
-#
+# Custom Dockerfile for BB-8 AI Inference
+# Extends the pre-built jetson-inference image to add websockets and SSL setup
 
-ARG BASE_IMAGE=nvcr.io/nvidia/l4t-pytorch:r32.4.3-pth1.6-py3
-FROM ${BASE_IMAGE}
+FROM dustynv/jetson-inference:r32.7.1
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV SHELL /bin/bash
+# 1. Install websockets
+RUN pip3 install websockets
 
-WORKDIR /jetson-inference
+# 2. Create entrypoint script
+RUN echo '#!/bin/bash' > /usr/local/bin/docker-entrypoint.sh && \
+    echo 'set -e' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '# 1. Save IP address' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'export JETSON_IP=$(ip -4 addr show wlan0 2>/dev/null | grep -oP "(?<=inet\s)\d+(\.\d+){3}" | head -n 1)' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'if [ -z "$JETSON_IP" ]; then' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '    export JETSON_IP=$(ip -4 addr show eth0 2>/dev/null | grep -oP "(?<=inet\s)\d+(\.\d+){3}" | head -n 1)' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'fi' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'echo "Detected JETSON_IP: $JETSON_IP"' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '# 2. Generate SSL Certs if missing' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'if [ ! -f /jetson-inference/data/key.pem ] || [ ! -f /jetson-inference/data/cert.pem ]; then' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '    echo "Generating SSL certificates..."' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '    openssl req -x509 -newkey rsa:4096 -keyout /jetson-inference/data/key.pem -out /jetson-inference/data/cert.pem -days 365 -nodes -subj "/CN=localhost" 2>/dev/null' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'fi' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'export SSL_KEY=/jetson-inference/data/key.pem' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'export SSL_CERT=/jetson-inference/data/cert.pem' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo '# Execute the passed command' >> /usr/local/bin/docker-entrypoint.sh && \
+    echo 'exec "$@"' >> /usr/local/bin/docker-entrypoint.sh && \
+    chmod +x /usr/local/bin/docker-entrypoint.sh
 
-  
-#
-# install development packages
-#
-RUN add-apt-repository --remove "deb https://apt.kitware.com/ubuntu/ $(lsb_release --codename --short) main" && \
-    apt-get update && \
-    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
-    apt-get install -y --no-install-recommends \
-            cmake \
-		  nano \
-		  mesa-utils \
-		  lsb-release \
-		  gstreamer1.0-tools \
-		  gstreamer1.0-libav \
-		  gstreamer1.0-rtsp \
-		  gstreamer1.0-plugins-good \
-		  gstreamer1.0-plugins-bad \
-		  gstreamer1.0-plugins-ugly \
-		  libgstreamer-plugins-base1.0-dev \
-		  libgstreamer-plugins-good1.0-dev \
-		  libgstreamer-plugins-bad1.0-dev && \
-    if [ `lsb_release --codename --short` != 'bionic' ]; then \
-    apt-get install -y --no-install-recommends \
-		  gstreamer1.0-plugins-rtp; \
-    else echo "skipping packages unavailable for Ubuntu 18.04"; fi \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
-
-# make a copy of this cause it gets purged...
-RUN mkdir -p /usr/local/include/gstreamer-1.0/gst && \
-    cp -r /usr/include/gstreamer-1.0/gst/webrtc /usr/local/include/gstreamer-1.0/gst && \
-    ls -ll /usr/local/include/ && \
-    ls -ll /usr/local/include/gstreamer-1.0/gst/webrtc
+ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
+CMD ["/bin/bash"]
 
 
-# 
-# install python packages
-#
-COPY python/training/detection/ssd/requirements.txt /tmp/pytorch_ssd_requirements.txt
-COPY python/www/flask/requirements.txt /tmp/flask_requirements.txt
-COPY python/www/dash/requirements.txt /tmp/dash_requirements.txt
-
-RUN pip3 install --no-cache-dir --verbose --upgrade Cython && \
-    pip3 install --no-cache-dir --verbose -r /tmp/pytorch_ssd_requirements.txt && \
-    pip3 install --no-cache-dir --verbose -r /tmp/flask_requirements.txt && \
-    pip3 install --no-cache-dir --verbose -r /tmp/dash_requirements.txt
-    
-    
-# 
-# install OpenCV (with CUDA)
-#
-ARG OPENCV_URL=https://nvidia.box.com/shared/static/5v89u6g5rb62fpz4lh0rz531ajo2t5ef.gz
-ARG OPENCV_DEB=OpenCV-4.5.0-aarch64.tar.gz
-
-COPY docker/containers/scripts/opencv_install.sh /tmp/opencv_install.sh
-RUN cd /tmp && ./opencv_install.sh ${OPENCV_URL} ${OPENCV_DEB}
-
-  
-#
-# copy source
-#
-COPY c c
-COPY examples examples
-COPY python python
-COPY tools tools
-COPY utils utils
-COPY data/networks/models.json data/networks/models.json
-
-COPY CMakeLists.txt CMakeLists.txt
-COPY CMakePreBuild.sh CMakePreBuild.sh
 
 
-#
-# build source
-#
-RUN mkdir docs && \
-    touch docs/CMakeLists.txt && \
-    sed -i 's/nvcaffe_parser/nvparsers/g' CMakeLists.txt && \
-    cp -r /usr/local/include/gstreamer-1.0/gst/webrtc /usr/include/gstreamer-1.0/gst && \
-    ln -s /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so.0 /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so && \
-    mkdir build && \
-    cd build && \
-    cmake ../ && \
-    make -j$(nproc) && \
-    make install && \
-    /bin/bash -O extglob -c "cd /jetson-inference/build; rm -rf -v !($(uname -m)|download-models.*)" && \
-    rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
-    
-# build out-of-tree samples
-RUN cd examples/my-recognition && \
-    mkdir build && \
-    cd build && \
-    cmake ../ && \
-    make
-
-# workaround for "cannot allocate memory in static TLS block"
-ENV LD_PRELOAD=${LD_PRELOAD}:/usr/lib/aarch64-linux-gnu/libgomp.so.1:/lib/aarch64-linux-gnu/libGLdispatch.so.0
